name = "Signals"
version = "0.1.0"
defaultTargets = ["Signals", "SignalsTests", "SignalsPending", "SignalsPendingTests"]

[[require]]
name = "Physlib"
path = "../physlib"

[[require]]
name = "mathlib"
path = "../mathlib4"

[[lean_lib]]
name = "Signals"

[[lean_lib]]
name = "SignalsTests"

[[lean_lib]]
name = "SignalsPending"

[[lean_lib]]
name = "SignalsPendingTests"
